# these controllers are only relevant for the gazebo simulation, which is deprecated

mobrob_robin:
  base:
    # Position Controllers ---------------------------------------
    x_position_controller:
      type: position_controllers/JointPositionController
      joint: base_x_joint
      pid: {p: 1.0}
      
    y_position_controller:
      type: position_controllers/JointPositionController
      joint: base_y_joint
      pid: {p: 1.0}
    
    yaw_position_controller:
      type: position_controllers/JointPositionController
      joint: base_yaw_joint
      pid: {p: 1.0}
    # Wheel Position Controllers ----------------------------------
    lf_position_controller:
      type: position_controllers/JointPositionController
      joint: wheel_lf_rot_z_joint
      pid: {p: 1.0}
      
    rb_position_controller:
      type: position_controllers/JointPositionController
      joint: wheel_rb_rot_z_joint
      pid: {p: 1.0}
    
    
