# this joint state publisher is only needed for the gazebo simulation

mobrob_robin:
# Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
