<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"> 
   <xacro:include filename="$(find mobrob_robin_description)/urdf/mobrob_robin_base/base.transmission.xacro" />     
   <xacro:macro name="base" params="">
      <link name="odom">
		 
         <inertial>
            <mass value="1" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
         </inertial>
         
      </link>
      <joint name="base_x_joint" type="prismatic">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <axis xyz="1 0 0" />
         <dynamics damping="0.0" friction="0.0" />
         <calibration rising="0.0" falling="0.0" />
         <limit effort="10" velocity="1.0" lower="-100" upper="100" />
         <parent link="odom" />
         <child link="base_x_link" />
      </joint>
      <link name="base_x_link">
         <inertial>
            <mass value="1" />
            <origin xyz="0 0 0.0" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
         </inertial>
      </link>
      <joint name="base_y_joint" type="prismatic">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <axis xyz="0 1 0" />
         <dynamics damping="0.0" friction="0.0" />
         <limit effort="10" velocity="1.0" lower="-100" upper="100" />
         <parent link="base_x_link" />
         <child link="base_y_link" />
      </joint>
      <link name="base_y_link">
         <inertial>
            <mass value="1" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
         </inertial>
      </link>
      
      <joint name="base_yaw_joint" type="continuous">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <axis xyz="0 0 1" />
         <dynamics damping="0.0" friction="0.0" />
         <limit effort="10" velocity="1.0" lower="-100" upper="100"/>
         <parent link="base_y_link" />
         <child link="base_link" />
      </joint> 

  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 ${base_height}" />
      <inertia ixx="${base_ixx}" ixy="0.0" ixz="0.0"
        iyy="${base_iyy}" iyz="0.0" izz="${base_izz}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${base_1_size_z/2 + base_height}" rpy="0 0 0" />
      <geometry>
        <!--<mesh scale="1.0 1.0 1.0 " filename="package://mobrob_robin_description/meshes/mobrob.stl"/>-->
        <box size="${base_1_size_x} ${base_1_size_y} ${base_1_size_z}" />
      </geometry>
      <material name="Gray_light" />
    </visual>

    <collision>
      <origin xyz="0 0 ${base_1_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_1_size_x} ${base_1_size_y} ${base_1_size_z}" />
      </geometry>
    </collision>
  </link>
  
  <joint name="base_upper_joint" type="fixed">
    <origin xyz="${base_2_size_x / 2 - base_1_size_x / 2} 0 ${base_1_size_z + base_height}" rpy="0 0 0" />        
    <parent link="base_link"/>
    <child link="base_upper_body" />
  </joint>
  
  <link name="base_upper_body">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0.0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${base_2_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_2_size_x} ${base_2_size_y} ${base_2_size_z}" />
        <!--<box size="0.001 0.001 0.001" />-->
      </geometry>
      <material name="Gray_light" />
    </visual>

    <collision>
      <origin xyz="0 0 ${base_2_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_2_size_x} ${base_2_size_y} ${base_2_size_z}" />
      </geometry>
    </collision>
  </link>
  
  


  <!--                         Wheel definition rotation z-axis                                        -->
    
  <!--wheel right front rotation z-axis-->
  <link name="wheel_rf_rot_z">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_small_long.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
      <material name="Gray_middle" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_small_long.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
    </collision>
  </link>
  
    <joint name="wheel_rf_rot_z_joint" type="fixed">
    <origin xyz="${wheel_rf_offset_x} ${wheel_rf_offset_y}  ${base_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="wheel_rf_rot_z"/>
  </joint>

  
    <!--wheel left back rotation z-axis-->
  <link name="wheel_lb_rot_z">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_small_long.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
      <material name="Gray_middle" />
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_small_long.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
    </collision>
  </link>
  
   <joint name="wheel_lb_rot_z_joint" type="fixed">
    <origin xyz="${wheel_lb_offset_x} ${wheel_lb_offset_y} ${base_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="wheel_lb_rot_z"/>
  </joint>
  
  
  <!--wheel left front rotation z-axis-->
  <link name="wheel_lf_rot_z">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_big.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
      <material name="Gray_middle" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_big.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
    </collision>
  </link>
  
  <joint name="wheel_lf_rot_z_joint" type="continuous">
  <dynamics damping="1.0" friction="0.0" />
    <origin xyz="${wheel_lf_offset_x} ${wheel_lf_offset_y} ${base_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="wheel_lf_rot_z"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <!--wheel right back rotation z-axis-->
  <link name="wheel_rb_rot_z">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.001" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_big.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
      <material name="Gray_middle" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_suspension_big.stl"/>
        <!--<box size="0.01 0.01 0.01" />-->
      </geometry>
    </collision>
  </link>

  <joint name="wheel_rb_rot_z_joint" type="continuous">
  <dynamics damping="1.0" friction="0.0" />
    <origin xyz="${wheel_rb_offset_x} ${wheel_rb_offset_y} ${base_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="wheel_rb_rot_z"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  
    <!--                         Wheel definition rotation y-axis                                        -->
    
    <!--wheel right front rotation y-axis-->
    <link name="wheel_rf_rot_y">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${wheel_small_mass}" />
      <inertia ixx="${wheel_small_ixx}" ixy="0.0" ixz="0.0"
        iyy="${wheel_small_iyy}" iyz="0.0" izz="${wheel_small_izz}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_small.stl"/>
      </geometry>
      <material name="Gray_dark" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_small_radius}" length = "${wheel_small_length}"/>
      </geometry>
    </collision>
  </link>
  
   <joint name="wheel_rf_rot_y_joint" type="fixed">
    <origin xyz="0 0 ${wheel_rf_offset_z}" rpy="0 0 0"/>
    <parent link="wheel_rf_rot_z"/>
    <child link="wheel_rf_rot_y"/>
  </joint>
    
    
     <!--wheel left back rotation y-axis-->
    <link name="wheel_lb_rot_y">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${wheel_small_mass}" />
      <inertia ixx="${wheel_small_ixx}" ixy="0.0" ixz="0.0"
        iyy="${wheel_small_iyy}" iyz="0.0" izz="${wheel_small_izz}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_small.stl"/>
      </geometry>
      <material name="Gray_dark" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_small_radius}" length = "${wheel_small_length}"/>
      </geometry>
    </collision>
  </link>
  
   <joint name="wheel_lb_rot_y_joint" type="fixed">
    <origin xyz="0 0 ${wheel_lb_offset_z}" rpy="0 0 0"/>
    <parent link="wheel_lb_rot_z"/>
    <child link="wheel_lb_rot_y"/>
  </joint>
  
  
       <!--wheel left front rotation y-axis-->
  <link name="wheel_lf_rot_y">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${wheel_big_mass}" />
      <inertia ixx="${wheel_big_ixx}" ixy="0.0" ixz="0.0"
        iyy="${wheel_big_iyy}" iyz="0.0" izz="${wheel_big_izz}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_big.stl"/>
      </geometry>
      <material name="Gray_dark" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_big_radius}" length = "${wheel_big_length}"/>
      </geometry>
    </collision>
  </link>
  
   <joint name="wheel_lf_rot_y_joint" type="fixed">
    <origin xyz="0 0 ${wheel_lf_offset_z}" rpy="0 0 0"/>
    <parent link="wheel_lf_rot_z"/>
    <child link="wheel_lf_rot_y"/>
  </joint>
  
         <!--wheel right back rotation y-axis-->
  <link name="wheel_rb_rot_y">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${wheel_big_mass}" />
      <inertia ixx="${wheel_big_ixx}" ixy="0.0" ixz="0.0"
        iyy="${wheel_big_iyy}" iyz="0.0" izz="${wheel_big_izz}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
      <geometry>
        <mesh scale="0.01 0.01 0.01 " filename="package://mobrob_robin_description/meshes/wheel_big.stl"/>
      </geometry>
      <material name="Gray_dark" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_big_radius}" length = "${wheel_big_length}"/>
      </geometry>
    </collision>
  </link>
  
   <joint name="wheel_rb_rot_y_joint" type="fixed">
   <dynamics damping="1.0" friction="0.0" />
    <origin xyz="0 0 ${wheel_rb_offset_z}" rpy="0 0 0"/>
    <parent link="wheel_rb_rot_z"/>
    <child link="wheel_rb_rot_y"/>
  </joint>
    
  <xacro:if value="${simulated}">		    	 
	<xacro:mobrob_transmission />         
  </xacro:if>      
      
   </xacro:macro>
</robot>

